### PR TITLE
Add duplicate error dialog on extraction

### PR DESCRIPTION
**Pull request by arnegns**

### CODE REVIEW

**Comment by arnegns** [comment]
Hi @PaulLereverend could you review this PR?

**Comment by clairton** [comment]
+1

**Comment by Loki-Afro** [comment]
any update on this?
@arnegns could you resolve those conflicts please?

@PaulLereverend ping :)

**Comment by PaulLereverend** [comment]
Sounds good to me if you can resolve the conflits

**Comment by arnegns** [comment]
@PaulLereverend master is merged. can you have a look?

**Comment by arnegns** [comment]
Hey @PaulLereverend can you please merge this pr?

**Comment by AntDavidLima** [comment]
Hey @arnegns , we recently took extract maintainance into our hands and would love to have the work you've done merged into the main branch, but sinse a lot of things changed from the last commit to now, we can't just merge it as it is.

Would you still be interested in updating this PR so it can be merged? If it is too much trouble for you, we will try to do our best to use the most of your contributions that we can.

**Pull request closed without merging**
